version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"                 #Porta do backend
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/workstream
    ports:
      - "3000:3000"                 #Porta do frontend
    volumes:                        #Permite mudanças direta no container
      - ./frontend/workstream:/usr/src/app

    networks:
      - app-network

networks: #Comunicacao entre front e back
  app-network:
    driver: bridge
